### ISSUE TITLE
Cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by bokov** [cattolyst/datafinisher#16]
For some .db files, `makesql.py` errors out as follows:

<pre>
 Traceback (most recent call last):
   File "makesql.py", line 555, in <module>
     main(con,csvfile,args.style,dtcp)
   File "makesql.py", line 439, in main
     where id in ("""+unkqryvars[2]+") group by patient_num,start_date,id"
 TypeError: cannot concatenate 'str' and 'NoneType' objects
</pre>

I suspect that this is because `unkqryvars[2]` is missing, and the code doesn't handle that currently. This error can be reproduced with the `pylori2.db` and `pylori3.db` input files.

**Comment by bokov** [comment]
The commit e00bc17..8fb2680 fixes this, but leaving ticket open-- need to detect this in one place, not in many by brute force.

**Comment by bokov** [comment]
I believe this is fixed via redesign. Let's see if ticket #10  (especially on `pylori2.db` and `pylori3.db`) confirms this in v0.2.1
